name: Run tests and upload coverage

on: 
  push

jobs:
  compile:
    name: Coverage
    runs-on: 'ubuntu-latest'
    steps:
        - uses: actions/checkout@v4
          with:
            submodules: true

        - uses: actions/cache@v4
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
            key: coverage-${{ hashFiles('**/Cargo.toml') }}

        - name: Install cargo-llvm-cov
          uses: taiki-e/install-action@cargo-llvm-cov
        - name: Install Protoc
          uses: arduino/setup-protoc@v3
          with:
            version: "23.x"
            repo-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Cargo test and coverage
          uses: clechasseur/rs-cargo@v3
          with:
            tool: cross
            command: 'llvm-cov'
            args: --codecov --output-path codecov.json

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v5
          if: ${{ !cancelled() }}
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: codecov.json
            fail_ci_if_error: true