name: Run tests and upload coverage

on: 
  push

jobs:
    coverage:
        name: Measure coverage
        runs-on: ubuntu-latest
        if: github.event_name != 'merge_group'
        steps:
          - name: Checkout sources
            uses: actions/checkout@v4
            with:
              persist-credentials: false
    
          - name: Install rust toolchain
            uses: dtolnay/rust-toolchain@stable
            with:
              components: llvm-tools
    
          - name: Install cargo-llvm-cov
            run: cargo install cargo-llvm-cov
    
          - name: Measure coverage
            run: ./admin/coverage --lcov --output-path final.info
    
          - name: Report to codecov.io
            uses: codecov/codecov-action@v5
            with:
              files: final.info
              token: ${{ secrets.CODECOV_TOKEN }}
              fail_ci_if_error: false